version: '{build}'

skip_tags: true

environment:
  matrix:
    - PYTHON_DIR: "C:\\Python37-x64"
      PY_VERSION: "py37"
    - PYTHON_DIR: "C:\\Python37"
      PY_VERSION: "py37"

install:
  - "%PYTHON_DIR%\\Scripts\\pip install --upgrade -e .[dev]"

build_script:
  - "%PYTHON_DIR%\\python setup.py clean --all"
  - "%PYTHON_DIR%\\python setup.py bdist_wheel --python-tag %PY_VERSION%"

test_script:
  - "%PYTHON_DIR%\\Scripts\\nose2 -c setup.cfg -v"
  - "%PYTHON_DIR%\\python setup.py check -v -r -m -s"
  - "%PYTHON_DIR%\\Scripts\\sphinx-build -b html ./doc/source/ ./doc/build/hml/"
  - "%PYTHON_DIR%\\Scripts\\sphinx-build -b linkcheck ./doc/source/ ./doc/build/linkcheck/"
